# Generated by Django 2.2.7 on 2020-02-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='cities',
            field=models.ManyToManyField(to='agg.city'),
        ),
    ]
